# Generated by Django 2.2 on 2019-04-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('veg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restraunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('owner_name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('delivery_time', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[['DELHI', 'DELHI'], ['Punjab', 'PUNJAB'], ['UP', 'UP'], ['HP', 'himachal'], ['Rajasthan', 'RAJASTHAN']], max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('veg', models.BooleanField(default=False)),
                ('mode_of_payment', models.CharField(default='', max_length=30)),
                ('offer', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.IntegerField(default=0)),
                ('menu', models.ManyToManyField(blank=True, to='products.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[['DELHI', 'DELHI'], ['Punjab', 'PUNJAB'], ['UP', 'UP'], ['HP', 'himachal'], ['Rajasthan', 'RAJASTHAN']], max_length=20)),
                ('about', models.TextField()),
                ('customer', models.BooleanField(default=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('cart', models.ManyToManyField(blank=True, to='products.Menu')),
                ('fav_restraunts', models.ManyToManyField(blank=True, related_name='fav_restraunts', to='products.Restraunt')),
                ('my_restraunts', models.ManyToManyField(blank=True, related_name='my_restraunts', to='products.Restraunt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restraunt_owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('restraunt', models.ManyToManyField(to='products.Restraunt')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restraunt',
            name='review',
            field=models.ManyToManyField(blank=True, to='products.Review'),
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Menu')),
                ('restraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Restraunt')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='new_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.ManyToManyField(blank=True, to='products.order_detail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
